onEvent('jei.hide.items', e => {
    e.hide('exnihilosequentia:andesite_crook')
    e.hide('exnihilosequentia:bone_crook')
    e.hide('exnihilosequentia:diamond_crook')
    e.hide('exnihilosequentia:diorite_crook')
    e.hide('exnihilosequentia:gold_crook')
    e.hide('exnihilosequentia:granite_crook')
    e.hide('exnihilosequentia:iron_crook')
    e.hide('exnihilosequentia:stone_crook')
    e.hide('exnihilosequentia:wooden_crook')

    e.hide('exnihilosequentia:diamond_hammer')
    e.hide('exnihilosequentia:golden_hammer')
    e.hide('exnihilosequentia:iron_hammer')
    e.hide('exnihilosequentia:netherite_hammer')
    e.hide('exnihilosequentia:stone_hammer')
    e.hide('exnihilosequentia:wooden_hammer')

    e.hide('exnihilosequentia:unfired_crucible')
    e.hide('exnihilosequentia:fired_crucible')
    e.hide('exnihilosequentia:birch_crucible')
    e.hide('exnihilosequentia:oak_crucible')
    e.hide('exnihilosequentia:acacia_crucible')
    e.hide('exnihilosequentia:spruce_crucible')
    e.hide('exnihilosequentia:jungle_crucible')
    e.hide('exnihilosequentia:warped_crucible')
    e.hide('exnihilosequentia:crimson_crucible')
    e.hide('exnihilosequentia:dark_oak_crucible')

    e.hide('exnihilosequentia:oak_barrel')
    e.hide('exnihilosequentia:dark_oak_barrel')
    e.hide('exnihilosequentia:birch_barrel')
    e.hide('exnihilosequentia:jungle_barrel')
    e.hide('exnihilosequentia:acacia_barrel')
    e.hide('exnihilosequentia:spruce_barrel')
    e.hide('exnihilosequentia:crimson_barrel')
    e.hide('exnihilosequentia:warped_barrel')
    e.hide('exnihilosequentia:stone_barrel')

    e.hide('exnihilosequentia:string_mesh')
    e.hide('exnihilosequentia:iron_mesh')
    e.hide('exnihilosequentia:diamond_mesh')
    e.hide('exnihilosequentia:flint_mesh')

    e.hide('exnihilosequentia:crafting_doll')
    e.hide('exnihilosequentia:blaze_doll')
    e.hide('exnihilosequentia:enderman_doll')
    e.hide('exnihilosequentia:shulker_doll')
    e.hide('exnihilosequentia:guardian_doll')
    e.hide('exnihilosequentia:bee_doll')

    e.hide('exnihilosequentia:cooked_silkworm')
    e.hide('exnihilosequentia:silkworm')
    
    e.hide('exnihilosequentia:andesite_pebble')
    e.hide('exnihilosequentia:basalt_pebble')
    e.hide('exnihilosequentia:blackstone_pebble')
    e.hide('exnihilosequentia:diorite_pebble')
    e.hide('exnihilosequentia:granite_pebble')
    e.hide('exnihilosequentia:stone_pebble')

    e.hide('exnihilosequentia:crushed_netherrack')
    e.hide('exnihilosequentia:crushed_end_stone')
    e.hide('exnihilosequentia:crushed_andesite')
    e.hide('exnihilosequentia:crushed_diorite')
    e.hide('exnihilosequentia:crushed_granite')

    e.hide('exnihilosequentia:iron_pieces')
    e.hide('exnihilosequentia:gold_pieces')
    e.hide('exnihilosequentia:copper_pieces')
    e.hide('exnihilosequentia:tin_pieces')
    e.hide('exnihilosequentia:zinc_pieces')
    e.hide('exnihilosequentia:lead_pieces')
    e.hide('exnihilosequentia:platinum_pieces')
    e.hide('exnihilosequentia:nickel_pieces')
    e.hide('exnihilosequentia:silver_pieces')
    e.hide('exnihilosequentia:aluminum_pieces')
    e.hide('exnihilosequentia:uranium_pieces')

    e.hide('exnihilosequentia:mycelium_spores')
    e.hide('exnihilosequentia:grass_seeds')
    e.hide('exnihilosequentia:oak_seeds')
    e.hide('exnihilosequentia:spruce_seeds')
    e.hide('exnihilosequentia:jungle_seeds')
    e.hide('exnihilosequentia:dark_oak_seeds')
    e.hide('exnihilosequentia:birch_seeds')
    e.hide('exnihilosequentia:acacia_seeds')
    e.hide('exnihilosequentia:cactus_seeds')
    e.hide('exnihilosequentia:sugarcane_seeds')
    e.hide('exnihilosequentia:carrot_seeds')
    e.hide('exnihilosequentia:potato_seeds')
    e.hide('exnihilosequentia:kelp_seeds')
    e.hide('exnihilosequentia:sweet_berry_seeds')
    e.hide('exnihilosequentia:pickle_seeds')
    e.hide('exnihilosequentia:bamboo_seeds')
    e.hide('exnihilosequentia:fern_seeds')
    e.hide('exnihilosequentia:large_fern_seeds')

    e.hide('exnihilosequentia:red_coral_larvae')
    e.hide('exnihilosequentia:pink_coral_larvae')
    e.hide('exnihilosequentia:yellow_coral_larvae')
    e.hide('exnihilosequentia:blue_coral_larvae')
    e.hide('exnihilosequentia:purple_coral_larvae')

    e.hide('exnihilosequentia:porcelain_clay')
    e.hide('exnihilosequentia:end_cake')
    e.hide('exnihilosequentia:beehive_frame')
    e.hide('exnihilosequentia:dust')
    e.hide('exnihilosequentia:infesting_leaves')
    e.hide('exnihilosequentia:infested_leaves')

    e.hide('exnihilosequentia:platinum_ingot')
    e.hide('exnihilosequentia:raw_platinum')
    e.hide('exnihilosequentia:raw_lead')
    e.hide('exnihilosequentia:raw_tin')
    e.hide('exnihilosequentia:raw_nickel')
    e.hide('exnihilosequentia:raw_silver')
    e.hide('exnihilosequentia:raw_aluminum')
    e.hide('exnihilosequentia:raw_uranium')
    e.hide('exnihilosequentia:raw_zinc')
})
