onEvent('jei.hide.items', e => {
    e.hide('thermal:dynamo_stirling')
    e.hide('thermal:dynamo_compression')
    e.hide('thermal:dynamo_magmatic')
    e.hide('thermal:dynamo_numismatic')
    e.hide('thermal:dynamo_lapidary')
    e.hide('thermal:dynamo_disenchantment')
    e.hide('thermal:dynamo_gourmand')
    e.hide('thermal:dynamo_output_augment')
    e.hide('thermal:dynamo_fuel_augment')
    e.hide('thermal:dynamo_throttle_augment')
    e.hide('thermal:apatite_ore')
    e.hide('thermal:deepslate_apatite_ore')
    e.hide('thermal:lead_ore')
    e.hide('thermal:deepslate_lead_ore')
    e.hide('thermal:nickel_ore')
    e.hide('thermal:deepslate_nickel_ore')
    e.hide('thermal:ruby_ore')
    e.hide('thermal:deepslate_ruby_ore')
    e.hide('thermal:sapphire_ore')
    e.hide('thermal:deepslate_sapphire_ore')
    e.hide('thermal:silver_ore')
    e.hide('thermal:deepslate_silver_ore')
    e.hide('thermal:sulfur_ore')
    e.hide('thermal:deepslate_sulfur_ore')
    e.hide('thermal:tin_ore')
    e.hide('thermal:deepslate_tin_ore')
})

onEvent('jei.remove.categories', event => {
	event.remove('thermal:disenchantment_fuel')
	event.remove('thermal:gourmand_fuel')
	event.remove('thermal:stirling_fuel')
})