onEvent('jei.hide.items', e => {
    e.hide('thermal:dynamo_stirling')
    e.hide('thermal:dynamo_compression')
    e.hide('thermal:dynamo_magmatic')
    e.hide('thermal:dynamo_numismatic')
    e.hide('thermal:dynamo_lapidary')
    e.hide('thermal:dynamo_disenchantment')
    e.hide('thermal:dynamo_gourmand')
    e.hide('thermal:dynamo_output_augment')
    e.hide('thermal:dynamo_fuel_augment')
    e.hide('thermal:dynamo_throttle_augment')
})