//priority: 899
/**
 *
 * @param {Internal.TagEventJS} biomeTagsEvent
 */
const setBiomeTags = (biomeTagsEvent) => {
  biomeTagsEvent.get("forge:is_overworld").add("tfc:badlands")
  biomeTagsEvent.get("forge:is_overworld").add("tfc:canyons")
  biomeTagsEvent.get("forge:is_overworld").add("tfc:deep_ocean")
  biomeTagsEvent.get("forge:is_overworld").add("tfc:deep_ocean_trench")
  biomeTagsEvent.get("forge:is_overworld").add("tfc:hills")
  biomeTagsEvent.get("forge:is_overworld").add("tfc:inverted_badlands")
  biomeTagsEvent.get("forge:is_overworld").add("tfc:lake")
  biomeTagsEvent.get("forge:is_overworld").add("tfc:lowlands")
  biomeTagsEvent.get("forge:is_overworld").add("tfc:low_canyons")
  biomeTagsEvent.get("forge:is_overworld").add("tfc:mountains")
  biomeTagsEvent.get("forge:is_overworld").add("tfc:mountain_lake")
  biomeTagsEvent.get("forge:is_overworld").add("tfc:mountain_river")
  biomeTagsEvent.get("forge:is_overworld").add("tfc:ocean")
  biomeTagsEvent.get("forge:is_overworld").add("tfc:oceanic_mountains")
  biomeTagsEvent.get("forge:is_overworld").add("tfc:oceanic_mountain_lake")
  biomeTagsEvent.get("forge:is_overworld").add("tfc:oceanic_mountain_river")
  biomeTagsEvent.get("forge:is_overworld").add("tfc:ocean_reef")
  biomeTagsEvent.get("forge:is_overworld").add("tfc:old_mountains")
  biomeTagsEvent.get("forge:is_overworld").add("tfc:old_mountain_lake")
  biomeTagsEvent.get("forge:is_overworld").add("tfc:old_mountain_river")
  biomeTagsEvent.get("forge:is_overworld").add("tfc:plains")
  biomeTagsEvent.get("forge:is_overworld").add("tfc:plateau")
  biomeTagsEvent.get("forge:is_overworld").add("tfc:plateau_lake")
  biomeTagsEvent.get("forge:is_overworld").add("tfc:river")
  biomeTagsEvent.get("forge:is_overworld").add("tfc:rolling_hills")
  biomeTagsEvent.get("forge:is_overworld").add("tfc:shore")
  biomeTagsEvent.get("forge:is_overworld").add("tfc:volcanic_mountains")
  biomeTagsEvent.get("forge:is_overworld").add("tfc:volcanic_mountain_lake")
  biomeTagsEvent.get("forge:is_overworld").add("tfc:volcanic_mountain_river")
  biomeTagsEvent.get("forge:is_overworld").add("tfc:volcanic_oceanic_mountains")
  biomeTagsEvent
    .get("forge:is_overworld")
    .add("tfc:volcanic_oceanic_mountain_lake")
  biomeTagsEvent
    .get("forge:is_overworld")
    .add("tfc:volcanic_oceanic_mountain_river")
}
