
#Wires
[wires]
	#Connector max input in FE/t (Energy transfer).
	#Range: > 0
	connector_max_input = 1024
	#Connector max output in FE/t (Energy transfer).
	#Range: > 0
	connector_max_output = 1024
	#Connector internal input buffer in FE.
	#Range: > 0
	connector_input_capacity = 2048
	#Ignore checking if block face can support connector.
	connector_ignore_face_check = false

#Portable Energy Interface
[portable_energy_interface]
	#PEI max output in FE/t (Energy transfer).
	#Range: > 0
	pei_max_output = 1024
	#PEI max input in FE/t (Energy transfer).
	#Range: > 0
	pei_max_input = 1024

#Electric Motor
[electric_motor]
	#Electric Motor internal capacity in FE.
	#Range: > 0
	motor_capacity = 2048
	#Electric Motor max input in FE (Energy transfer not consumption).
	#Range: > 0
	motor_max_input = 256

#Alternator
[alternator]
	#Alternator internal capacity in FE.
	#Range: > 0
	generator_capacity = 2048
	#Alternator max input in FE (Energy transfer, not generation).
	#Range: > 0
	generator_max_output = 256

#Accumulator
[accumulator]
	#Accumulator internal capacity per block in FE.
	#Range: > 0
	accumulator_capacity = 4196000
	#Accumulator max output in FE/t (Energy transfer).
	#Range: > 0
	accumulator_max_output = 512
	#Accumulator max input in FE/t (Energy transfer).
	#Range: > 0
	accumulator_max_input = 512

