
#.
#Client-only settings - If you're looking for general settings, look inside your worlds serverconfig folder!
[client]
	#Show kinetic debug information on blocks while the F3-Menu is open.
	enableRainbowDebug = true
	#Offset the Create config button in the main menu by this many pixels on the X axis
	#The sign (-/+) of this value determines what side of the row the button appears on (left/right)
	#Range: > -2147483648
	mainMenuConfigButtonOffsetX = -40000
