
#Wires
[wires]
	#Connector max input in FE/t (Energy transfer).
	#Range: > 0
	connector_max_input = 1000
	#Connector max output in FE/t (Energy transfer).
	#Range: > 0
	connector_max_output = 1000
	#Connector internal input buffer in FE.
	#Range: > 0
	connector_input_capacity = 1000
	#Ignore checking if block face can support connector.
	connector_ignore_face_check = false

#Portable Energy Interface
[portable_energy_interface]
	#PEI max output in FE/t (Energy transfer).
	#Range: > 0
	pei_max_output = 1000
	#PEI max input in FE/t (Energy transfer).
	#Range: > 0
	pei_max_input = 1000

#Alternator
[alternator]
	#Alternator internal capacity in FE.
	#Range: > 0
	generator_capacity = 2000
	#Alternator max input in FE (Energy transfer, not generation).
	#Range: > 0
	generator_max_output = 300

#Accumulator
[accumulator]
	#Accumulator internal capacity per block in FE.
	#Range: > 0
	accumulator_capacity = 4000000
	#Accumulator max output in FE/t (Energy transfer).
	#Range: > 0
	accumulator_max_output = 600
	#Accumulator max input in FE/t (Energy transfer).
	#Range: > 0
	accumulator_max_input = 600

