#Disables most lighting code for certain models that are rendered dynamically (TESR). May improve FPS.
#Affects turrets and garden cloches
disableFancyTESR = true
#Use VBOs to render certain blocks. This is significantly faster than the usual rendering,
#but may not work correctly with visual effects from other mods
enableVBO = false
