
["Dragon Structure Options"]

	["Dragon Structure Options"."Coal Dragon Structure Options"]
		#
		#Coal Dragon Structure Dimensions (Example: minecraft:overworld, minecraft:nether)
		coalDragonStructureDimensions = "minecraft:overworld"
		#
		#Coal Dragon Structure Biomes (Example: mushroom_fields, swamp; Put * for every biome)
		coalDragonStructureBiomes = "*"

	["Dragon Structure Options"."Copper Dragon Structure Options"]
		#
		#Copper Dragon Structure Dimensions (Example: minecraft:overworld, minecraft:nether)
		copperDragonStructureDimensions = "minecraft:overworld"
		#
		#Copper Dragon Structure Biomes (Example: mushroom_fields, swamp; Put * for every biome)
		copperDragonStructureBiomes = "*"

	["Dragon Structure Options"."Iron Dragon Structure Options"]
		#
		#Iron Dragon Structure Dimensions (Example: minecraft:overworld, minecraft:nether)
		ironDragonStructureDimensions = "minecraft:overworld"
		#
		#Iron Dragon Structure Biomes (Example: mushroom_fields, swamp; Put * for every biome)
		ironDragonStructureBiomes = "*"

	["Dragon Structure Options"."Gold Dragon Structure Options"]
		#
		#Gold Dragon Structure Dimensions (Example: minecraft:overworld, minecraft:nether)
		goldDragonStructureDimensions = "minecraft:overworld"
		#
		#Gold Dragon Structure Biomes (Example: mushroom_fields, swamp; Put * for every biome)
		goldDragonStructureBiomes = "*"

	["Dragon Structure Options"."Redstone Dragon Structure Options"]
		#
		#Redstone Dragon Structure Dimensions (Example: minecraft:overworld, minecraft:nether)
		redstoneDragonStructureDimensions = "minecraft:overworld"
		#
		#Redstone Dragon Structure Biomes (Example: mushroom_fields, swamp; Put * for every biome)
		redstoneDragonStructureBiomes = "*"

	["Dragon Structure Options"."Lapis Dragon Structure Options"]
		#
		#Lapis Dragon Structure Dimensions (Example: minecraft:overworld, minecraft:nether)
		lapisDragonStructureDimensions = "minecraft:overworld"
		#
		#Lapis Dragon Structure Biomes (Example: mushroom_fields, swamp; Put * for every biome)
		lapisDragonStructureBiomes = "*"

	["Dragon Structure Options"."Diamond Dragon Structure Options"]
		#
		#Diamond Dragon Structure Dimensions (Example: minecraft:overworld, minecraft:nether)
		diamondDragonStructureDimensions = "minecraft:overworld"
		#
		#Diamond Dragon Structure Biomes (Example: mushroom_fields, swamp; Put * for every biome)
		diamondDragonStructureBiomes = "*"

	["Dragon Structure Options"."Emerald Dragon Structure Options"]
		#
		#Emerald Dragon Structure Dimensions (Example: minecraft:overworld, minecraft:nether)
		emeraldDragonStructureDimensions = "minecraft:overworld"
		#
		#Emerald Dragon Structure Biomes (Example: mushroom_fields, swamp; Put * for every biome)
		emeraldDragonStructureBiomes = "*"

	["Dragon Structure Options"."Obsidian Dragon Structure Options"]
		#
		#Obsidian Dragon Structure Dimensions (Example: minecraft:overworld, minecraft:nether)
		obsidianDragonStructureDimensions = "minecraft:overworld"
		#
		#Obsidian Dragon Structure Biomes (Example: mushroom_fields, swamp; Put * for every biome)
		obsidianDragonStructureBiomes = "mushroom_fields, badlands_plateau"

	["Dragon Structure Options"."Netherite Dragon Structure Options"]
		#
		#Netherite Dragon Structure Dimensions (Example: minecraft:overworld, minecraft:nether)
		netheriteDragonStructureDimensions = "minecraft:nether"
		#
		#Netherite Dragon Structure Biomes (Example: mushroom_fields, swamp; Put * for every biome)
		netheriteDragonStructureBiomes = "*"

	["Dragon Structure Options"."Allthemodium Dragon Structure Options **Not implemented yet**"]
		#
		#Allthemodium Dragon Structure Dimensions (Example: minecraft:overworld, minecraft:nether)
		allthemodiumDragonStructureDimensions = "minecraft:overworld"
		#
		#Allthemodium Dragon Structure Biomes (Example: mushroom_fields, swamp; Put * for every biome)
		allthemodiumDragonStructureBiomes = "*"

	["Dragon Structure Options"."Vibranium Dragon Structure Options **Not implemented yet**"]
		#
		#Vibranium Dragon Structure Dimensions (Example: minecraft:overworld, minecraft:nether)
		vibraniumDragonStructureDimensions = "minecraft:overworld"
		#
		#Vibranium Dragon Structure Biomes (Example: mushroom_fields, swamp; Put * for every biome)
		vibraniumDragonStructureBiomes = "*"

	["Dragon Structure Options"."Unobtainium Dragon Structure Options **Not implemented yet**"]
		#
		#Unobtainium Dragon Structure Dimensions (Example: minecraft:overworld, minecraft:nether)
		unobtainiumDragonStructureDimensions = "minecraft:overworld"
		#
		#Unobtainium Dragon Structure Biomes (Example: mushroom_fields, swamp; Put * for every biome)
		unobtainiumDragonStructureBiomes = "*"

	["Dragon Structure Options"."Dracolich Dragon Structure Options **Not implemented yet**"]
		#
		#Dracolich Dragon Structure Dimensions (Example: minecraft:overworld, minecraft:nether)
		dracolichDragonStructureDimensions = "minecraft:overworld"
		#
		#Dracolich Dragon Structure Biomes (Example: mushroom_fields, swamp; Put * for every biome)
		dracolichDragonStructureBiomes = "*"

["Dragon Options"]

	["Dragon Options"."Coal Dragon Options"]
		#
		#Coal Dragon Max Health
		#Range: 1.0 ~ 1.7976931348623157E308
		coalDragonMaxHealth = 800.0
		#
		#Coal Dragon Armor
		#Range: 1.0 ~ 1.7976931348623157E308
		coalDragonArmor = 5.0
		#
		#Coal Dragon Attack Damage
		#Range: 1.0 ~ 1.7976931348623157E308
		coalDragonAttackDamage = 8.5

	["Dragon Options"."Copper Dragon Options"]
		#
		#Copper Dragon Max Health
		#Range: 1.0 ~ 1.7976931348623157E308
		copperDragonMaxHealth = 1200.0
		#
		#Copper Dragon Armor
		#Range: 1.0 ~ 1.7976931348623157E308
		copperDragonArmor = 5.5
		#
		#Copper Dragon Attack Damage
		#Range: 1.0 ~ 1.7976931348623157E308
		copperDragonAttackDamage = 9.0

	["Dragon Options"."Iron Dragon Options"]
		#
		#Iron Dragon Max Health
		#Range: 1.0 ~ 1.7976931348623157E308
		ironDragonMaxHealth = 1800.0
		#
		#Iron Dragon Armor
		#Range: 1.0 ~ 1.7976931348623157E308
		ironDragonArmor = 6.0
		#
		#Iron Dragon Attack Damage
		#Range: 1.0 ~ 1.7976931348623157E308
		ironDragonAttackDamage = 9.5

	["Dragon Options"."Gold Dragon Options"]
		#
		#Gold Dragon Max Health
		#Range: 1.0 ~ 1.7976931348623157E308
		goldDragonMaxHealth = 2500.0
		#
		#Gold Dragon Armor
		#Range: 1.0 ~ 1.7976931348623157E308
		goldDragonArmor = 5.5
		#
		#Gold Dragon Attack Damage
		#Range: 1.0 ~ 1.7976931348623157E308
		goldDragonAttackDamage = 9.5

	["Dragon Options"."Redstone Dragon Options"]
		#
		#Redstone Dragon Max Health
		#Range: 1.0 ~ 1.7976931348623157E308
		redstoneDragonMaxHealth = 2700.0
		#
		#Redstone Dragon Armor
		#Range: 1.0 ~ 1.7976931348623157E308
		redstoneDragonArmor = 6.0
		#
		#Redstone Dragon Attack Damage
		#Range: 1.0 ~ 1.7976931348623157E308
		redstoneDragonAttackDamage = 10.0

	["Dragon Options"."Lapis Dragon Options"]
		#
		#Lapis Dragon Max Health
		#Range: 1.0 ~ 1.7976931348623157E308
		lapisDragonMaxHealth = 3000.0
		#
		#Lapis Dragon Armor
		#Range: 1.0 ~ 1.7976931348623157E308
		lapisDragonArmor = 6.5
		#
		#Lapis Dragon Attack Damage
		#Range: 1.0 ~ 1.7976931348623157E308
		lapisDragonAttackDamage = 10.5

	["Dragon Options"."Diamond Dragon Options"]
		#
		#Diamond Dragon Max Health
		#Range: 1.0 ~ 1.7976931348623157E308
		diamondDragonMaxHealth = 3500.0
		#
		#Diamond Dragon Armor
		#Range: 1.0 ~ 1.7976931348623157E308
		diamondDragonArmor = 7.0
		#
		#Diamond Dragon Attack Damage
		#Range: 1.0 ~ 1.7976931348623157E308
		diamondDragonAttackDamage = 11.0

	["Dragon Options"."Emerald Dragon Options"]
		#
		#Emerald Dragon Max Health
		#Range: 1.0 ~ 1.7976931348623157E308
		emeraldDragonMaxHealth = 3500.0
		#
		#Emerald Dragon Armor
		#Range: 1.0 ~ 1.7976931348623157E308
		emeraldDragonArmor = 7.5
		#
		#Emerald Dragon Attack Damage
		#Range: 1.0 ~ 1.7976931348623157E308
		emeraldDragonAttackDamage = 12.0

	["Dragon Options"."Obsidian Dragon Options"]
		#
		#Obsidian Dragon Max Health
		#Range: 1.0 ~ 1.7976931348623157E308
		obsidianDragonMaxHealth = 4200.0
		#
		#Obsidian Dragon Armor
		#Range: 1.0 ~ 1.7976931348623157E308
		obsidianDragonArmor = 8.0
		#
		#Obsidian Dragon Attack Damage
		#Range: 1.0 ~ 1.7976931348623157E308
		obsidianDragonAttackDamage = 12.5

	["Dragon Options"."Netherite Dragon Options"]
		#
		#Netherite Dragon Max Health
		#Range: 1.0 ~ 1.7976931348623157E308
		netheriteDragonMaxHealth = 5500.0
		#
		#Netherite Dragon Armor
		#Range: 1.0 ~ 1.7976931348623157E308
		netheriteDragonArmor = 9.0
		#
		#Netherite Dragon Attack Damage
		#Range: 1.0 ~ 1.7976931348623157E308
		netheriteDragonAttackDamage = 14.0

	["Dragon Options"."Allthemodium Dragon Options **Not implemented yet**"]
		#
		#Allthemodium Dragon Max Health
		#Range: 1.0 ~ 1.7976931348623157E308
		allthemodiumDragonMaxHealth = 10000.0
		#
		#Allthemodium Dragon Armor
		#Range: 1.0 ~ 1.7976931348623157E308
		allthemodiumDragonArmor = 10.0
		#
		#Allthemodium Dragon Attack Damage
		#Range: 1.0 ~ 1.7976931348623157E308
		allthemodiumDragonAttackDamage = 12.0

	["Dragon Options"."Vibranium Dragon Options **Not implemented yet**"]
		#
		#Vibranium Dragon Max Health
		#Range: 1.0 ~ 1.7976931348623157E308
		vibraniumDragonMaxHealth = 20000.0
		#
		#Vibranium Dragon Armor
		#Range: 1.0 ~ 1.7976931348623157E308
		vibraniumDragonArmor = 12.0
		#
		#Vibranium Dragon Attack Damage
		#Range: 1.0 ~ 1.7976931348623157E308
		vibraniumDragonAttackDamage = 14.0

	["Dragon Options"."Unobtainium Dragon Options **Not implemented yet**"]
		#
		#Unobtainium Dragon Max Health
		#Range: 1.0 ~ 1.7976931348623157E308
		unobtainiumDragonMaxHealth = 30000.0
		#
		#Unobtainium Dragon Armor
		#Range: 1.0 ~ 1.7976931348623157E308
		unobtainiumDragonArmor = 15.0
		#
		#Unobtainium Dragon Attack Damage
		#Range: 1.0 ~ 1.7976931348623157E308
		unobtainiumDragonAttackDamage = 18.0

	["Dragon Options"."Dracolich Dragon Options **Not implemented yet**"]
		#
		#Dracolich Dragon Max Health
		#Range: 1.0 ~ 1.7976931348623157E308
		dracolichDragonMaxHealth = 50000.0
		#
		#Dracolich Dragon Armor
		#Range: 1.0 ~ 1.7976931348623157E308
		dracolichDragonArmor = 20.0
		#
		#Dracolich Dragon Attack Damage
		#Range: 1.0 ~ 1.7976931348623157E308
		dracolichDragonAttackDamage = 25.0

["Breath Options"]

	["Breath Options"."Ice Breath Options"]
		#
		#Ice Breath Damage
		#Range: > 1
		iceBreathDamage = 5
		#
		#Ice Breath Seconds Freeze
		#Range: 1.0 ~ 1.7976931348623157E308
		iceBreathSecondsFreeze = 2.5

	["Breath Options"."Fire Breath Options"]
		#
		#Fire Breath Damage
		#Range: > 1
		fireBreathDamage = 5
		#
		#Fire Breath Seconds on Fire
		#Range: > 1
		fireBreathSecondsOnFire = 5

	["Breath Options"."Lightning Breath Options"]
		#
		#Lightning Breath Damage
		#Range: > 1
		lightningBreathDamage = 5

	["Breath Options"."Radiation Breath Options"]
		#
		#Radiation Breath Damage
		#Range: > 1
		radiationBreathDamage = 5
		#
		#Radiation Breath Splash Range
		#Range: 1.0 ~ 1.7976931348623157E308
		radiationBreathSplashRange = 4.0
		#
		#Radiation Breath Seconds Radiation
		#Range: > 1
		radiationBreathSecondsRadiation = 5
		#
		#Radiation Breath Radiation Amplifier
		#Range: > 1
		radiationBreathRadiationAmplifier = 1

	["Breath Options"."Poison Breath Options"]
		#
		#Poison Breath Splash Range
		#Range: 1.0 ~ 1.7976931348623157E308
		poisonBreathSplashRange = 4.0
		#
		#Poison Breath Seconds Poison
		#Range: > 1
		poisonBreathSecondsRadiation = 4
		#
		#Poison Breath Poison Amplifier
		#Range: > 1
		poisonBreathRadiationAmplifier = 3

	["Breath Options"."Acid Breath Options"]
		#
		#Acid Breath Damage
		#Range: > 1
		acidBreathDamage = 5
		#
		#Acid Breath Seconds Acid
		#Range: > 1
		acidBreathSecondsAcid = 4
		#
		#Acid Breath Acid Amplifier
		#Range: > 1
		acidBreathAcidAmplifier = 1

	["Breath Options"."Withering Breath Options"]
		#
		#Withering Breath Damage
		#Range: > 1
		witheringBreathDamage = 5
		#
		#Withering Breath Seconds Wither
		#Range: > 1
		witheringBreathSecondsWither = 4
		#
		#Withering Breath Wither Amplifier
		#Range: > 1
		witheringBreathWitherAmplifier = 4

	["Breath Options"."Drain Breath Options"]
		#
		#Drain Breath Damage
		#Range: > 1
		drainBreathDamage = 5
		#
		#Drain Breath Seconds Drain
		#Range: > 1
		drainBreathSecondsDrain = 8
		#
		#Drain Breath Drain Amplifier
		#Range: > 1
		drainBreathDrainAmplifier = 4

	["Breath Options"."Disenchanting Breath Options"]
		#
		#Disenchanting Breath Damage
		#Range: > 1
		disenchantingBreathDamage = 5

["Effect Options"]

	["Effect Options"."Radiation Effect Options"]
		#
		#Radiation Effect Damage Amount
		#Range: > 1
		radiationEffectDamageAmount = 10

	["Effect Options"."Acid Effect Options"]
		#
		#Acid Effect Damage Amount
		#Range: 1.0 ~ 1.7976931348623157E308
		acidEffectDamageAmount = 1.5
		#
		#Acid Effect Damage Cooldown in Seconds
		#Range: 1.0 ~ 1.7976931348623157E308
		acidEffectDamageCooldown = 0.2
		#
		#Acid Effect Enchanted Damage Amount
		#Range: > 1
		acidEffectEnchantedDamageAmount = 2
		#
		#Acid Effect not Enchanted Damage Amount
		#Range: > 1
		acidEffectNotEnchantedDamageAmount = 3

	["Effect Options"."Drain Effect Options"]
		#
		#Drain Effect Drain Amount
		#Range: > 1
		drainEffectDrainAmount = 5000

["Structure Options"]
	#
	#Dragon Cave Chest Weight 
	#Higher Value -> Less Chests
	#Range: > 1
	dragonCaveChestWeight = 80
	#
	#Dragon Cave Shell Block (Example: minecraft:tnt, leave empty if you do not want an extra shell)
	dragonCaveShellBlock = "tfc:rock/bricks/granite"

["Debug Options"]
	#
	#Print spawned Dragon Caves into the console
	printSpawnedDragonCavesConsole = false

