
[World]

	[World.Ores]

		[World.Ores."Oil Sand"]
			#Max number of veins per chunk; set to 0 to disable.
			#Range: 0 ~ 64
			"Vein Count" = 0

		[World.Ores.Silver]
			#Max number of veins per chunk; set to 0 to disable.
			#Range: 0 ~ 64
			"Vein Count" = 0

		[World.Ores.Lead]
			#Max number of veins per chunk; set to 0 to disable.
			#Range: 0 ~ 64
			"Vein Count" = 0

		[World.Ores.Nickel]
			#Max number of veins per chunk; set to 0 to disable.
			#Range: 0 ~ 64
			"Vein Count" = 0

		[World.Ores.Cinnabar]
			#Max number of veins per chunk; set to 0 to disable.
			#Range: 0 ~ 64
			"Vein Count" = 0

		[World.Ores.Sulfur]
			#Max number of veins per chunk; set to 0 to disable.
			#Range: 0 ~ 64
			"Vein Count" = 0

		[World.Ores.Tin]
			#Max number of veins per chunk; set to 0 to disable.
			#Range: 0 ~ 64
			"Vein Count" = 0

		[World.Ores.Niter]
			#Max number of veins per chunk; set to 0 to disable.
			#Range: 0 ~ 64
			"Vein Count" = 0

