#Miscellaneous options
[general]
	#Beneficial effects that can't used by certain features such as ankh of pray, lollipop, scroll of preservation, alchemy perk and magic siphon enchantment
	unhandled_beneficial_effects = ["astralsorcery:potiontimefreeze", "potionsmaster:osmiumpotioneffect", "potionsmaster:vibraniumpotioneffect", "potionsmaster:allthemodiumpotioneffect", "potionsmaster:platinumpotioneffect", "potionsmaster:uraniumpotioneffect", "potionsmaster:leadpotioneffect", "potionsmaster:crimsonironpotioneffect", "potionsmaster:unobtainiumpotioneffect"]

#For settings related to decorative tombs and magic items
[decorative_grave]
	#Allows the merchant grave gardian [false/true|default:true]
	allow_grave_gardian = false

#Options related to looted items
[loot]
	#Entities that can't found as loot in a Familiar Receptacle
	unhandled_tameable_entities = ["Vibranium Dragon","Unobtainium Dragon","Allthemodium Dragon"]
