
#Options related to player's death
[player_death]
	#The time in minutes before a grave is unlocked to anyone (-1 = disabled) [-1..MAX|default:-1]
	#Range: > -1
	decay_time = 60

#Allows to disable some magic items
[allowedMagicItems]
	#Lost Tablet [false/true|default:true]
	allow_lost_tablet = false

