
[xpCost]
	#The maximum base xp cost (may be exceeded by multipliers defined below), set to 0 to disable all distance-based XP costs
	#Range: -1.7976931348623157E308 ~ 1.7976931348623157E308
	maximumBaseXpCost = 0.0

[restrictions]
	#List of dimensions that players are allowed to warp cross-dimension from and to. If left empty, all dimensions except those in dimensionalWarpDenyList are allowed.
	dimensionalWarpAllowList = ["minecraft:overworld", "minecraft:the_nether"]
